"""empty message

Revision ID: 77a717e59466
Revises: fd6069c2628d
Create Date: 2022-08-11 12:18:52.432575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77a717e59466'
down_revision = 'fd6069c2628d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Area',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('address', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('State',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('area_state',
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['Area.id'], ),
    sa.ForeignKeyConstraint(['state_id'], ['State.id'], ),
    sa.PrimaryKeyConstraint('area_id', 'state_id')
    )
    op.add_column('Venue', sa.Column('area_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Venue', 'Area', ['area_id'], ['id'])
    op.drop_column('Venue', 'address')
    op.drop_column('Venue', 'city')
    op.drop_column('Venue', 'state')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('state', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('Venue', sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('Venue', sa.Column('address', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Venue', type_='foreignkey')
    op.drop_column('Venue', 'area_id')
    op.drop_table('area_state')
    op.drop_table('State')
    op.drop_table('Area')
    # ### end Alembic commands ###
